spring:
#  datasource:
#    name: test
#    url: jdbc:mysql://10.8.27.70:3306/mcp?verifyServerCertificate=false&useSSL=false&requireSSL=false
#    username: root
#    password: eastcom
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  zipkin:
    base-url: http://mcp-monitor
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 10.8.29.53
    port: 5672
    username: mcp
    password: 123456
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    uaa:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders: null
      serviceId: mcp-authentication
logging:
  level:
    root: INFO
security:
  oauth2:
    client:
      access-token-uri: http://10.8.29.41:8020/uaa/oauth/token
      user-authorization-uri: http://10.8.29.41:8020/uaa/oauth/authorize
    resource:
      user-info-uri: http://10.8.29.41:8020/uaa/user
      prefer-token-info: false
management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh
        - hystrix.stream
        - info
        - health
