spring:
  zipkin:
    base-url: http://mcp-monitor
    sender:
      type: web
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  rabbitmq:
    host: 10.8.29.53
    port: 5672
    username: mcp
    password: 123456
  datasource:
    name: test
    url: jdbc:mysql://10.8.27.70:3306/mcp?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: eastcom
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 10.8.29.52
    port: 6379
    password: AS@redis
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1
        max-wait: -1
logging:
  level:
    root: info
    com.eastcom.mcp.monitor: debug
    com.netflix.turbine: info
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8020/uaa/user
      prefer-token-info: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.eastcom.mcp.monitor.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh
        - hystrix.stream
        - info
        - health
        - clusters
  metrics:
    web:
      server:
        auto-time-requests: false
turbine:
  app-config: mcp-dictionary, mcp-resource, mcp-alarm, mcp-api, mcp-application, mcp-authentication, mcp-backup, mcp-config, mcp-consumer,mcp-discovery,mcp-dispatcher,mcp-gateway,mcp-job,mcp-log,mcp-monitor,mcp-policy,mcp-protocal,mcp-provider,mcp-role,mcp-scene,mcp-user
  combine-host-port: true
  aggregator:
    cluster-config:
    - MCP-DICTIONARY
    - MCP-RESOURCE
    - MCP-ALARM
    - MCP-API
    - MCP-APPLICATION
    - MCP-AUTHENTICATION
    - MCP-BACKUP
    - MCP-CONFIG
    - MCP-CONSUMER
    - MCP-DISCOVERY
    - MCP-DISPATCHER
    - MCP-GATEWAY
    - MCP-JOB
    - MCP-LOG
    - MCP-MONITOR
    - MCP-POLICY
    - MCP-PROTOCAL
    - MCP-PROVIDER
    - MCP-ROLE
    - MCP-SCENE
    - MCP-USER
