spring:
  rabbitmq:
    host: 10.8.29.53
    port: 5672
    username: mcp
    password: 123456
  datasource:
    name: test
    url: jdbc:mysql://10.8.27.70:3306/mcp?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: eastcom
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 10.8.29.52
    port: 6379
    password: AS@redis
    expireMinutes: 2
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1
        max-wait: -1
management:
  endpoint:
    hystrix:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
security:
  oauth2:
    resource:
      user-info-uri: http://10.8.29.41:8020/uaa/user
      prefer-token-info: false
    client:
      access-token-uri: http://10.8.29.41:8020/uaa/oauth/token
      client-id: microservice
      client-secret: webApp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eastcom.mcp.demo.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
